Y™Áäx-ÆÈ‹j◊ù¢Îi∫⁄+äßj[hëÈ‹¢ÈÌ„ø8NãZñã≠¶Îeäw¨’•µ¡Ω…–ÅIïÖç–∞ÅÏÅ’Õïôôïç–∞Å’ÕïM—Ö—îÅÙÅô…Ω¥Äâ…ïÖç–àÏ)•µ¡Ω…–ÅÏÅΩ…µA…ΩŸ•ëï»∞Å’ÕïΩ…¥ÅÙÅô…Ω¥Äâ…ïÖç–µ°ΩΩ¨µôΩ…¥àÏ)•µ¡Ω…–ÅÏÅÈΩëIïÕΩ±Ÿï»ÅÙÅô…Ω¥Äâ°ΩΩ≠ôΩ…¥Ω…ïÕΩ±Ÿï…ÃΩÈΩêàÏ)•µ¡Ω…–ÅÏÅËÅÙÅô…Ω¥ÄâÈΩêàÏ)•µ¡Ω…–ÅM›Ö∞Åô…Ω¥ÄâÕ›ïï—Ö±ï…–»àÏ)•µ¡Ω…–ÅÏÅ’Õï1ΩçÖ—•Ω∏∞Å’Õï9ÖŸ•ùÖ—îÅÙÅô…Ω¥Äâ…ïÖç–µ…Ω’—ï»µëΩ¥àÏ)•µ¡Ω…–ÅÏÅ•±ïQï·–∞ÅMÖŸî∞ÅU¡±ΩÖê∞Å`ÅÙÅô…Ω¥Äâ±’ç•ëîµ…ïÖç–àÏ)•µ¡Ω…–ÅÏÅÕ—Ω…ÖùïMï…Ÿ•çîÅÙÅô…Ω¥Äà∏∏ΩÕï…Ÿ•çïÃΩÕ—Ω…ÖùïMï…Ÿ•çîàÏ)•µ¡Ω…–ÅÏÅÕÕï–∞Å——Öç°µïπ–∞ÅÖ—ïùΩ…‰∞Å1ΩçÖ—•Ω∏∞ÅA…•Ω…•—‰∞ÅA…ΩŸ•ëï»∞ÅIï≈’ïÕ–∞ÅUπ•–∞ÅUÕï»∞Å]Ω…≠=…ëï»∞Å]Ω…≠=…ëï…M—Ö—’ÃÅÙÅô…Ω¥Äà∏∏Ω—Â¡ïÃàÏ)•µ¡Ω…–ÅÏÅ	’——Ω∏ÅÙÅô…Ω¥Äà∏∏ΩçΩµ¡Ωπïπ—ÃΩ’§Ω	’——Ω∏àÏ)•µ¡Ω…–ÅÏÅÖ…ê∞ÅÖ…ëΩπ—ïπ–∞ÅÖ…ëΩΩ—ï»ÅÙÅô…Ω¥Äà∏∏ΩçΩµ¡Ωπïπ—ÃΩ’§ΩÖ…êàÏ)•µ¡Ω…–ÅÏÅ%π¡’–ÅÙÅô…Ω¥Äà∏∏ΩçΩµ¡Ωπïπ—ÃΩ’§Ω%π¡’–àÏ)•µ¡Ω…–ÅÏÅMï±ïç–ÅÙÅô…Ω¥Äà∏∏ΩçΩµ¡Ωπïπ—ÃΩ’§ΩMï±ïç–àÏ)•µ¡Ω…–ÅÏÅQï·—Ö…ïÑÅÙÅô…Ω¥Äà∏∏ΩçΩµ¡Ωπïπ—ÃΩ’§ΩQï·—Ö…ïÑàÏ)•µ¡Ω…–ÅÏÅ=¡ï…Ö—•ΩπÖ±AÖùï!ïÖëï»ÅÙÅô…Ω¥Äà∏∏ΩçΩµ¡Ωπïπ—ÃΩ’§Ω=¡ï…Ö—•ΩπÖ±AÖùîàÏ)•µ¡Ω…–ÅÏÅQÖâÕΩµ¡Ωπïπ–ÅÙÅô…Ω¥Äà∏∏ΩçΩµ¡Ωπïπ—ÃΩ’§ΩQÖâÕΩµ¡Ωπïπ–àÏ)•µ¡Ω…–ÅÏÅ’Õï’—†ÅÙÅô…Ω¥Äà∏∏ΩçΩπ—ï·—ÃΩ’—°Ωπ—ï·–àÏ()çΩπÕ–ÅΩÕMç°ïµÑÄÙÅËπΩâ©ïç–°Ï(ÄÅ’π•—%êËÅËπÕ—…•πú†§πµ•∏†ƒ∞ÄâMï±ïç•ΩπîÅÑÅ’π•ëÖëî∏à§∞(ÄÅ±ΩçÖ—•Ωπ%êËÅËπÕ—…•πú†§πµ•∏†ƒ∞ÄâMï±ïç•ΩπîÅºÅ±ΩçÖ∞ÅΩ‘ÅÖµâ•ïπ—î∏à§∞(ÄÅÕïç—Ω»ËÅËπÕ—…•πú†§πΩ¡—•ΩπÖ∞†§∞(ÄÅÖÕÕï—%ëÃËÅËπÖ……Ö‰°ËπÕ—…•πú†§§∞(ÄÅ—Â¡îËÅËπÕ—…•πú†§πµ•∏†ƒ∞ÄâMï±ïç•ΩπîÅºÅ—•¡ºÅëîÅÕï…Ÿßùº∏à§∞(ÄÅçÖ—ïùΩ…Â%êËÅËπÕ—…•πú†§πµ•∏†ƒ∞ÄâMï±ïç•ΩπîÅÑÅçÖ—ïùΩ…•Ñ∏à§∞(ÄÅ¡…•Ω…•—‰ËÅËπïπ’¥°lâ	Ö•·Ñà∞Äâ7•ë•Ñà∞Äâ±—Ñà∞ÄâU…ùïπ—îât§∞(ÄÅ—ïç°π•çÖ±ïÕç…•¡—•Ω∏ËÅËπÕ—…•πú†§π—…•¥†§πµ•∏†ƒ¿∞ÄâïÕç…ïŸÑÅºÅÕï…ŸßùºÅçΩ¥Å¡ï±ºÅµïπΩÃÄƒ¿ÅçÖ…Öç—ï…ïÃ∏à§∞(ÄÅ…ó~¸‚⁄$z{-ÆÈ‹j◊ùdf" onChange={(event) => setFiles((current) => [...current, ...Array.from(event.target.files || [])])} /></label></div>{files.length > 0 && <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{files.map((file, index) => <div key={`${file.name}-${index}`} className="flex items-center gap-3 rounded-md border border-slate-200 bg-slate-50 p-3"><FileText className="h-5 w-5 text-slate-500" /><span className="min-w-0 flex-1 truncate text-sm">{file.name}</span><button type="button" aria-label={`Remover ${file.name}`} onClick={() => setFiles((current) => current.filter((_, fileIndex) => fileIndex !== index))} className="rounded p-1 text-red-700 hover:bg-red-50"><X className="h-4 w-4" /></button></div>)}</div>}<div className="rounded-md border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700"><strong>Revis√£o antes de salvar</strong><p className="mt-1">O salvamento √© √∫nico. Ap√≥s criar, a OS seguir√° para programa√ß√£o, execu√ß√£o, valida√ß√£o e encerramento na pr√≥pria ficha.</p></div></div> },
              ]} />
            </CardContent>
            <CardFooter className="justify-end gap-3 border-t border-slate-200 px-6 py-4"><Button type="button" variant="secondary" onClick={() => navigate(-1)}>Cancelar</Button><Button type="submit" disabled={!isValid || isSubmitting} className="gap-2"><Save className="h-4 w-4" />{isSubmitting ? "Salvando..." : "Salvar Ordem de Servi√ßo"}</Button></CardFooter>
          </Card>
        </form>
      </FormProvider>
    </div>
  );
};
